# Generated by Django 5.2 on 2025-05-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_usuarioprofile_user'),
    ]

    operations = [
    ]
