# Generated by Django 5.2 on 2025-05-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20250510_1615'),
        ('shop', '0006_auto_20250510_1617'),
    ]

    operations = [
    ]
