# Generated by Django 5.2 on 2025-05-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_merge_0005_auto_20250510_1615_0006_auto_20250510_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioprofile',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tipousuario'),
        ),
    ]
